import NavigationMore from "@/icons/navigation-more.vue";
import LoadBalancer from "@/icons/load-balancer.vue";
import Shuffle from "@/icons/shuffle.vue";
import CheckmarkOutline from "@/icons/checkmark-outline.vue";
import Copy from "@/icons/copy.vue";
import ViewTile from "@/icons/view-tile.vue";
import BrightnessDown from "@/icons/brightness-down.vue";
import MoodSadOutline from "@/icons/mood-sad-outline.vue";
import HandStop from "@/icons/hand-stop.vue";
import Code from "@/icons/code.vue";
import Queue from "@/icons/queue.vue";
import LockOpen from "@/icons/lock-open.vue";
import Keyboard from "@/icons/keyboard.vue";
import WindowNew from "@/icons/window-new.vue";
import Checkmark from "@/icons/checkmark.vue";
import Vector from "@/icons/vector.vue";
import BatteryFull from "@/icons/battery-full.vue";
import ArrowThickUp from "@/icons/arrow-thick-up.vue";
import TravelTaxiCab from "@/icons/travel-taxi-cab.vue";
import Wallet from "@/icons/wallet.vue";
import ChartPie from "@/icons/chart-pie.vue";
import BorderOuter from "@/icons/border-outer.vue";
import DialPad from "@/icons/dial-pad.vue";
import Backspace from "@/icons/backspace.vue";
import Bug from "@/icons/bug.vue";
import TravelBus from "@/icons/travel-bus.vue";
import PenTool from "@/icons/pen-tool.vue";
import Dashboard from "@/icons/dashboard.vue";
import StandBy from "@/icons/stand-by.vue";
import UserSolidCircle from "@/icons/user-solid-circle.vue";
import Cloud from "@/icons/cloud.vue";
import AlignLeft from "@/icons/align-left.vue";
import LocationPark from "@/icons/location-park.vue";
import Adjust from "@/icons/adjust.vue";
import AlignCenter from "@/icons/align-center.vue";
import Time from "@/icons/time.vue";
import SubdirectoryRight from "@/icons/subdirectory-right.vue";
import ArrowThinLeft from "@/icons/arrow-thin-left.vue";
import ArrowRight from "@/icons/arrow-right.vue";
import SaveDisk from "@/icons/save-disk.vue";
import CloudUpload from "@/icons/cloud-upload.vue";
import ArrowThickLeft from "@/icons/arrow-thick-left.vue";
import EditCut from "@/icons/edit-cut.vue";
import ComputerDesktop from "@/icons/computer-desktop.vue";
import BrightnessUp from "@/icons/brightness-up.vue";
import ArrowThinUp from "@/icons/arrow-thin-up.vue";
import Notifications from "@/icons/notifications.vue";
import Mouse from "@/icons/mouse.vue";
import ThumbsUp from "@/icons/thumbs-up.vue";
import BorderNone from "@/icons/border-none.vue";
import FastForward from "@/icons/fast-forward.vue";
import IndentDecrease from "@/icons/indent-decrease.vue";
import BrowserWindowNew from "@/icons/browser-window-new.vue";
import Paste from "@/icons/paste.vue";
import ArrowOutlineRight from "@/icons/arrow-outline-right.vue";
import StrokeWidth from "@/icons/stroke-width.vue";
import VolumeMute from "@/icons/volume-mute.vue";
import Directions from "@/icons/directions.vue";
import Share from "@/icons/share.vue";
import EditCrop from "@/icons/edit-crop.vue";
import StoreFront from "@/icons/store-front.vue";
import BookmarkOutlineAdd from "@/icons/bookmark-outline-add.vue";
import LocationHotel from "@/icons/location-hotel.vue";
import Apparel from "@/icons/apparel.vue";
import Document from "@/icons/document.vue";
import MinusSolid from "@/icons/minus-solid.vue";
import CreditCard from "@/icons/credit-card.vue";
import TravelCar from "@/icons/travel-car.vue";
import PauseOutline from "@/icons/pause-outline.vue";
import Radar from "@/icons/radar.vue";
import BorderRight from "@/icons/border-right.vue";
import Usb from "@/icons/usb.vue";
import InboxCheck from "@/icons/inbox-check.vue";
import YinYang from "@/icons/yin-yang.vue";
import StarFull from "@/icons/star-full.vue";
import MinusOutline from "@/icons/minus-outline.vue";
import Badge from "@/icons/badge.vue";
import ReplyAll from "@/icons/reply-all.vue";
import Portfolio from "@/icons/portfolio.vue";
import FolderOutline from "@/icons/folder-outline.vue";
import Film from "@/icons/film.vue";
import Close from "@/icons/close.vue";
import Tablet from "@/icons/tablet.vue";
import AddSolid from "@/icons/add-solid.vue";
import VolumeUp from "@/icons/volume-up.vue";
import ArrowOutlineUp from "@/icons/arrow-outline-up.vue";
import LocationMarina from "@/icons/location-marina.vue";
import Calendar from "@/icons/calendar.vue";
import Playlist from "@/icons/playlist.vue";
import ChatBubbleDots from "@/icons/chat-bubble-dots.vue";
import Clipboard from "@/icons/clipboard.vue";
import BorderTop from "@/icons/border-top.vue";
import Translate from "@/icons/translate.vue";
import StepForward from "@/icons/step-forward.vue";
import BorderVertical from "@/icons/border-vertical.vue";
import Servers from "@/icons/servers.vue";
import Backward from "@/icons/backward.vue";
import AlignJustified from "@/icons/align-justified.vue";
import Pylon from "@/icons/pylon.vue";
import CheveronOutlineUp from "@/icons/cheveron-outline-up.vue";
import Station from "@/icons/station.vue";
import BackwardStep from "@/icons/backward-step.vue";
import Hot from "@/icons/hot.vue";
import MoodNeutralSolid from "@/icons/mood-neutral-solid.vue";
import ScreenFull from "@/icons/screen-full.vue";
import Inbox from "@/icons/inbox.vue";
import CheveronOutlineLeft from "@/icons/cheveron-outline-left.vue";
import Duplicate from "@/icons/duplicate.vue";
import Stethoscope from "@/icons/stethoscope.vue";
import CloseSolid from "@/icons/close-solid.vue";
import Tag from "@/icons/tag.vue";
import Chart from "@/icons/chart.vue";
import Printer from "@/icons/printer.vue";
import Map from "@/icons/map.vue";
import ListBullet from "@/icons/list-bullet.vue";
import Airplane from "@/icons/airplane.vue";
import Location from "@/icons/location.vue";
import CheveronLeft from "@/icons/cheveron-left.vue";
import Explore from "@/icons/explore.vue";
import LocationCurrent from "@/icons/location-current.vue";
import List from "@/icons/list.vue";
import Gift from "@/icons/gift.vue";
import BookmarkOutline from "@/icons/bookmark-outline.vue";
import MoodHappySolid from "@/icons/mood-happy-solid.vue";
import UserSolidSquare from "@/icons/user-solid-square.vue";
import Reload from "@/icons/reload.vue";
import FormatItalic from "@/icons/format-italic.vue";
import ViewCarousel from "@/icons/view-carousel.vue";
import TravelCase from "@/icons/travel-case.vue";
import Trophy from "@/icons/trophy.vue";
import LocationRestroom from "@/icons/location-restroom.vue";
import InboxDownload from "@/icons/inbox-download.vue";
import ArrowThinRight from "@/icons/arrow-thin-right.vue";
import ExclamationOutline from "@/icons/exclamation-outline.vue";
import EditPencil from "@/icons/edit-pencil.vue";
import Cog from "@/icons/cog.vue";
import Globe from "@/icons/globe.vue";
import Box from "@/icons/box.vue";
import Travel from "@/icons/travel.vue";
import WindowOpen from "@/icons/window-open.vue";
import ShareAlt from "@/icons/share-alt.vue";
import VolumeDown from "@/icons/volume-down.vue";
import Network from "@/icons/network.vue";
import ArrowThinDown from "@/icons/arrow-thin-down.vue";
import Bolt from "@/icons/bolt.vue";
import UserGroup from "@/icons/user-group.vue";
import Home from "@/icons/home.vue";
import ToolsCopy from "@/icons/tools copy.vue";
import BookReference from "@/icons/book-reference.vue";
import Flag from "@/icons/flag.vue";
import Conversation from "@/icons/conversation.vue";
import CheveronOutlineDown from "@/icons/cheveron-outline-down.vue";
import MusicAlbum from "@/icons/music-album.vue";
import ViewColumn from "@/icons/view-column.vue";
import MobileDevices from "@/icons/mobile-devices.vue";
import PhpElephant from "@/icons/php-elephant.vue";
import LightBulb from "@/icons/light-bulb.vue";
import Repost from "@/icons/repost.vue";
import Album from "@/icons/album.vue";
import LockClosed from "@/icons/lock-closed.vue";
import NotificationsOutline from "@/icons/notifications-outline.vue";
import Watch from "@/icons/watch.vue";
import FastRewind from "@/icons/fast-rewind.vue";
import Filter from "@/icons/filter.vue";
import MoodSadSolid from "@/icons/mood-sad-solid.vue";
import BorderLeft from "@/icons/border-left.vue";
import InboxFull from "@/icons/inbox-full.vue";
import BatteryHalf from "@/icons/battery-half.vue";
import Menu from "@/icons/menu.vue";
import ShoppingCart from "@/icons/shopping-cart.vue";
import Announcement from "@/icons/announcement.vue";
import AddOutline from "@/icons/add-outline.vue";
import Trash from "@/icons/trash.vue";
import BorderAll from "@/icons/border-all.vue";
import Factory from "@/icons/factory.vue";
import Send from "@/icons/send.vue";
import ViewList from "@/icons/view-list.vue";
import BrowserWindow from "@/icons/browser-window.vue";
import Heart from "@/icons/heart.vue";
import Share01 from "@/icons/share-01.vue";
import Bookmark from "@/icons/bookmark.vue";
import UserAdd from "@/icons/user-add.vue";
import MusicNotes from "@/icons/music-notes.vue";
import User from "@/icons/user.vue";
import Anchor from "@/icons/anchor.vue";
import Block from "@/icons/block.vue";
import Radio from "@/icons/radio.vue";
import Attachment from "@/icons/attachment.vue";
import VolumeOff from "@/icons/volume-off.vue";
import Search from "@/icons/search.vue";
import Library from "@/icons/library.vue";
import BookmarkCopy2 from "@/icons/bookmark copy 2.vue";
import ArrowDown from "@/icons/arrow-down.vue";
import Layers from "@/icons/layers.vue";
import Compose from "@/icons/compose.vue";
import StepBackward from "@/icons/step-backward.vue";
import TextDecoration from "@/icons/text-decoration.vue";
import Pin from "@/icons/pin.vue";
import BookmarkCopy3 from "@/icons/bookmark copy 3.vue";
import Headphones from "@/icons/headphones.vue";
import HourGlass from "@/icons/hour-glass.vue";
import Wrench from "@/icons/wrench.vue";
import Swap from "@/icons/swap.vue";
import Pause from "@/icons/pause.vue";
import CheveronUp from "@/icons/cheveron-up.vue";
import Tuning from "@/icons/tuning.vue";
import MusicArtist from "@/icons/music-artist.vue";
import ArrowOutlineLeft from "@/icons/arrow-outline-left.vue";
import Play from "@/icons/play.vue";
import ForwardStep from "@/icons/forward-step.vue";
import DotsHorizontalTriple from "@/icons/dots-horizontal-triple.vue";
import SubdirectoryLeft from "@/icons/subdirectory-left.vue";
import FormatBold from "@/icons/format-bold.vue";
import ArrowUp from "@/icons/arrow-up.vue";
import FormatUnderline from "@/icons/format-underline.vue";
import ComputerLaptop from "@/icons/computer-laptop.vue";
import DocumentAdd from "@/icons/document-add.vue";
import LocationGasStation from "@/icons/location-gas-station.vue";
import AtSymbol from "@/icons/at-symbol.vue";
import ViewHide from "@/icons/view-hide.vue";
import Mic from "@/icons/mic.vue";
import ShowSidebar from "@/icons/show-sidebar.vue";
import Timer from "@/icons/timer.vue";
import BorderBottom from "@/icons/border-bottom.vue";
import ArrowOutlineDown from "@/icons/arrow-outline-down.vue";
import DotsHorizontalDouble from "@/icons/dots-horizontal-double.vue";
import ZoomIn from "@/icons/zoom-in.vue";
import InformationOutline from "@/icons/information-outline.vue";
import Target from "@/icons/target.vue";
import Key from "@/icons/key.vue";
import BrowserWindowOpen from "@/icons/browser-window-open.vue";
import Forward from "@/icons/forward.vue";
import HardDrive from "@/icons/hard-drive.vue";
import PauseSolid from "@/icons/pause-solid.vue";
import AlignRight from "@/icons/align-right.vue";
import IndentIncrease from "@/icons/indent-increase.vue";
import Question from "@/icons/question.vue";
import TextBox from "@/icons/text-box.vue";
import Link from "@/icons/link.vue";
import FormatFontSize from "@/icons/format-font-size.vue";
import ColorPalette from "@/icons/color-palette.vue";
import MoodNeutralOutline from "@/icons/mood-neutral-outline.vue";
import Flashlight from "@/icons/flashlight.vue";
import ArrowThickRight from "@/icons/arrow-thick-right.vue";
import BatteryLow from "@/icons/battery-low.vue";
import Folder from "@/icons/folder.vue";
import Ticket from "@/icons/ticket.vue";
import ChartBar from "@/icons/chart-bar.vue";
import Plugin from "@/icons/plugin.vue";
import ZoomOut from "@/icons/zoom-out.vue";
import Thermometer from "@/icons/thermometer.vue";
import ThumbsDown from "@/icons/thumbs-down.vue";
import Reply from "@/icons/reply.vue";
import ArrowThickDown from "@/icons/arrow-thick-down.vue";
import CheveronDown from "@/icons/cheveron-down.vue";
import Buoy from "@/icons/buoy.vue";
import MusicPlaylist from "@/icons/music-playlist.vue";
import NewsPaper from "@/icons/news-paper.vue";
import Photo from "@/icons/photo.vue";
import CheveronOutlineRight from "@/icons/cheveron-outline-right.vue";
import BorderInner from "@/icons/border-inner.vue";
import Camera from "@/icons/camera.vue";
import Envelope from "@/icons/envelope.vue";
import BorderHorizontal from "@/icons/border-horizontal.vue";
import Window from "@/icons/window.vue";
import ViewShow from "@/icons/view-show.vue";
import Coffee from "@/icons/coffee.vue";
import Artist from "@/icons/artist.vue";
import Refresh from "@/icons/refresh.vue";
import TravelWalk from "@/icons/travel-walk.vue";
import ListAdd from "@/icons/list-add.vue";
import PlayOutline from "@/icons/play-outline.vue";
import Beverage from "@/icons/beverage.vue";
import LocationFood from "@/icons/location-food.vue";
import Phone from "@/icons/phone.vue";
import VideoCamera from "@/icons/video-camera.vue";
import FolderOutlineAdd from "@/icons/folder-outline-add.vue";
import Bluetooth from "@/icons/bluetooth.vue";
import CloseOutline from "@/icons/close-outline.vue";
import ExclamationSolid from "@/icons/exclamation-solid.vue";
import InformationSolid from "@/icons/information-solid.vue";
import LocationShopping from "@/icons/location-shopping.vue";
import EditCopy from "@/icons/edit-copy.vue";
import Notification from "@/icons/notification.vue";
import Shield from "@/icons/shield.vue";
import DateAdd from "@/icons/date-add.vue";
import ArrowLeft from "@/icons/arrow-left.vue";
import Education from "@/icons/education.vue";
import TravelTrain from "@/icons/travel-train.vue";
import MoodHappyOutline from "@/icons/mood-happy-outline.vue";
import Download from "@/icons/download.vue";
import Calculator from "@/icons/calculator.vue";
import Upload from "@/icons/upload.vue";
import FormatTextSize from "@/icons/format-text-size.vue";
import CheveronRight from "@/icons/cheveron-right.vue";
import CurrencyDollar from "@/icons/currency-dollar.vue";
export default (app) => {
	app.component("NavigationMore", NavigationMore);
	app.component("LoadBalancer", LoadBalancer);
	app.component("Shuffle", Shuffle);
	app.component("CheckmarkOutline", CheckmarkOutline);
	app.component("Copy", Copy);
	app.component("ViewTile", ViewTile);
	app.component("BrightnessDown", BrightnessDown);
	app.component("MoodSadOutline", MoodSadOutline);
	app.component("HandStop", HandStop);
	app.component("Code", Code);
	app.component("Queue", Queue);
	app.component("LockOpen", LockOpen);
	app.component("Keyboard", Keyboard);
	app.component("WindowNew", WindowNew);
	app.component("Checkmark", Checkmark);
	app.component("Vector", Vector);
	app.component("BatteryFull", BatteryFull);
	app.component("ArrowThickUp", ArrowThickUp);
	app.component("TravelTaxiCab", TravelTaxiCab);
	app.component("Wallet", Wallet);
	app.component("ChartPie", ChartPie);
	app.component("BorderOuter", BorderOuter);
	app.component("DialPad", DialPad);
	app.component("Backspace", Backspace);
	app.component("Bug", Bug);
	app.component("TravelBus", TravelBus);
	app.component("PenTool", PenTool);
	app.component("Dashboard", Dashboard);
	app.component("StandBy", StandBy);
	app.component("UserSolidCircle", UserSolidCircle);
	app.component("Cloud", Cloud);
	app.component("AlignLeft", AlignLeft);
	app.component("LocationPark", LocationPark);
	app.component("Adjust", Adjust);
	app.component("AlignCenter", AlignCenter);
	app.component("Time", Time);
	app.component("SubdirectoryRight", SubdirectoryRight);
	app.component("ArrowThinLeft", ArrowThinLeft);
	app.component("ArrowRight", ArrowRight);
	app.component("SaveDisk", SaveDisk);
	app.component("CloudUpload", CloudUpload);
	app.component("ArrowThickLeft", ArrowThickLeft);
	app.component("EditCut", EditCut);
	app.component("ComputerDesktop", ComputerDesktop);
	app.component("BrightnessUp", BrightnessUp);
	app.component("ArrowThinUp", ArrowThinUp);
	app.component("Notifications", Notifications);
	app.component("Mouse", Mouse);
	app.component("ThumbsUp", ThumbsUp);
	app.component("BorderNone", BorderNone);
	app.component("FastForward", FastForward);
	app.component("IndentDecrease", IndentDecrease);
	app.component("BrowserWindowNew", BrowserWindowNew);
	app.component("Paste", Paste);
	app.component("ArrowOutlineRight", ArrowOutlineRight);
	app.component("StrokeWidth", StrokeWidth);
	app.component("VolumeMute", VolumeMute);
	app.component("Directions", Directions);
	app.component("Share", Share);
	app.component("EditCrop", EditCrop);
	app.component("StoreFront", StoreFront);
	app.component("BookmarkOutlineAdd", BookmarkOutlineAdd);
	app.component("LocationHotel", LocationHotel);
	app.component("Apparel", Apparel);
	app.component("Document", Document);
	app.component("MinusSolid", MinusSolid);
	app.component("CreditCard", CreditCard);
	app.component("TravelCar", TravelCar);
	app.component("PauseOutline", PauseOutline);
	app.component("Radar", Radar);
	app.component("BorderRight", BorderRight);
	app.component("Usb", Usb);
	app.component("InboxCheck", InboxCheck);
	app.component("YinYang", YinYang);
	app.component("StarFull", StarFull);
	app.component("MinusOutline", MinusOutline);
	app.component("Badge", Badge);
	app.component("ReplyAll", ReplyAll);
	app.component("Portfolio", Portfolio);
	app.component("FolderOutline", FolderOutline);
	app.component("Film", Film);
	app.component("Close", Close);
	app.component("Tablet", Tablet);
	app.component("AddSolid", AddSolid);
	app.component("VolumeUp", VolumeUp);
	app.component("ArrowOutlineUp", ArrowOutlineUp);
	app.component("LocationMarina", LocationMarina);
	app.component("Calendar", Calendar);
	app.component("Playlist", Playlist);
	app.component("ChatBubbleDots", ChatBubbleDots);
	app.component("Clipboard", Clipboard);
	app.component("BorderTop", BorderTop);
	app.component("Translate", Translate);
	app.component("StepForward", StepForward);
	app.component("BorderVertical", BorderVertical);
	app.component("Servers", Servers);
	app.component("Backward", Backward);
	app.component("AlignJustified", AlignJustified);
	app.component("Pylon", Pylon);
	app.component("CheveronOutlineUp", CheveronOutlineUp);
	app.component("Station", Station);
	app.component("BackwardStep", BackwardStep);
	app.component("Hot", Hot);
	app.component("MoodNeutralSolid", MoodNeutralSolid);
	app.component("ScreenFull", ScreenFull);
	app.component("Inbox", Inbox);
	app.component("CheveronOutlineLeft", CheveronOutlineLeft);
	app.component("Duplicate", Duplicate);
	app.component("Stethoscope", Stethoscope);
	app.component("CloseSolid", CloseSolid);
	app.component("Tag", Tag);
	app.component("Chart", Chart);
	app.component("Printer", Printer);
	app.component("Map", Map);
	app.component("ListBullet", ListBullet);
	app.component("Airplane", Airplane);
	app.component("Location", Location);
	app.component("CheveronLeft", CheveronLeft);
	app.component("Explore", Explore);
	app.component("LocationCurrent", LocationCurrent);
	app.component("List", List);
	app.component("Gift", Gift);
	app.component("BookmarkOutline", BookmarkOutline);
	app.component("MoodHappySolid", MoodHappySolid);
	app.component("UserSolidSquare", UserSolidSquare);
	app.component("Reload", Reload);
	app.component("FormatItalic", FormatItalic);
	app.component("ViewCarousel", ViewCarousel);
	app.component("TravelCase", TravelCase);
	app.component("Trophy", Trophy);
	app.component("LocationRestroom", LocationRestroom);
	app.component("InboxDownload", InboxDownload);
	app.component("ArrowThinRight", ArrowThinRight);
	app.component("ExclamationOutline", ExclamationOutline);
	app.component("EditPencil", EditPencil);
	app.component("Cog", Cog);
	app.component("Globe", Globe);
	app.component("Box", Box);
	app.component("Travel", Travel);
	app.component("WindowOpen", WindowOpen);
	app.component("ShareAlt", ShareAlt);
	app.component("VolumeDown", VolumeDown);
	app.component("Network", Network);
	app.component("ArrowThinDown", ArrowThinDown);
	app.component("Bolt", Bolt);
	app.component("UserGroup", UserGroup);
	app.component("Home", Home);
	app.component("ToolsCopy", ToolsCopy);
	app.component("BookReference", BookReference);
	app.component("Flag", Flag);
	app.component("Conversation", Conversation);
	app.component("CheveronOutlineDown", CheveronOutlineDown);
	app.component("MusicAlbum", MusicAlbum);
	app.component("ViewColumn", ViewColumn);
	app.component("MobileDevices", MobileDevices);
	app.component("PhpElephant", PhpElephant);
	app.component("LightBulb", LightBulb);
	app.component("Repost", Repost);
	app.component("Album", Album);
	app.component("LockClosed", LockClosed);
	app.component("NotificationsOutline", NotificationsOutline);
	app.component("Watch", Watch);
	app.component("FastRewind", FastRewind);
	app.component("Filter", Filter);
	app.component("MoodSadSolid", MoodSadSolid);
	app.component("BorderLeft", BorderLeft);
	app.component("InboxFull", InboxFull);
	app.component("BatteryHalf", BatteryHalf);
	app.component("Menu", Menu);
	app.component("ShoppingCart", ShoppingCart);
	app.component("Announcement", Announcement);
	app.component("AddOutline", AddOutline);
	app.component("Trash", Trash);
	app.component("BorderAll", BorderAll);
	app.component("Factory", Factory);
	app.component("Send", Send);
	app.component("ViewList", ViewList);
	app.component("BrowserWindow", BrowserWindow);
	app.component("Heart", Heart);
	app.component("Share01", Share01);
	app.component("Bookmark", Bookmark);
	app.component("UserAdd", UserAdd);
	app.component("MusicNotes", MusicNotes);
	app.component("User", User);
	app.component("Anchor", Anchor);
	app.component("Block", Block);
	app.component("Radio", Radio);
	app.component("Attachment", Attachment);
	app.component("VolumeOff", VolumeOff);
	app.component("Search", Search);
	app.component("Library", Library);
	app.component("BookmarkCopy2", BookmarkCopy2);
	app.component("ArrowDown", ArrowDown);
	app.component("Layers", Layers);
	app.component("Compose", Compose);
	app.component("StepBackward", StepBackward);
	app.component("TextDecoration", TextDecoration);
	app.component("Pin", Pin);
	app.component("BookmarkCopy3", BookmarkCopy3);
	app.component("Headphones", Headphones);
	app.component("HourGlass", HourGlass);
	app.component("Wrench", Wrench);
	app.component("Swap", Swap);
	app.component("Pause", Pause);
	app.component("CheveronUp", CheveronUp);
	app.component("Tuning", Tuning);
	app.component("MusicArtist", MusicArtist);
	app.component("ArrowOutlineLeft", ArrowOutlineLeft);
	app.component("Play", Play);
	app.component("ForwardStep", ForwardStep);
	app.component("DotsHorizontalTriple", DotsHorizontalTriple);
	app.component("SubdirectoryLeft", SubdirectoryLeft);
	app.component("FormatBold", FormatBold);
	app.component("ArrowUp", ArrowUp);
	app.component("FormatUnderline", FormatUnderline);
	app.component("ComputerLaptop", ComputerLaptop);
	app.component("DocumentAdd", DocumentAdd);
	app.component("LocationGasStation", LocationGasStation);
	app.component("AtSymbol", AtSymbol);
	app.component("ViewHide", ViewHide);
	app.component("Mic", Mic);
	app.component("ShowSidebar", ShowSidebar);
	app.component("Timer", Timer);
	app.component("BorderBottom", BorderBottom);
	app.component("ArrowOutlineDown", ArrowOutlineDown);
	app.component("DotsHorizontalDouble", DotsHorizontalDouble);
	app.component("ZoomIn", ZoomIn);
	app.component("InformationOutline", InformationOutline);
	app.component("Target", Target);
	app.component("Key", Key);
	app.component("BrowserWindowOpen", BrowserWindowOpen);
	app.component("Forward", Forward);
	app.component("HardDrive", HardDrive);
	app.component("PauseSolid", PauseSolid);
	app.component("AlignRight", AlignRight);
	app.component("IndentIncrease", IndentIncrease);
	app.component("Question", Question);
	app.component("TextBox", TextBox);
	app.component("Link", Link);
	app.component("FormatFontSize", FormatFontSize);
	app.component("ColorPalette", ColorPalette);
	app.component("MoodNeutralOutline", MoodNeutralOutline);
	app.component("Flashlight", Flashlight);
	app.component("ArrowThickRight", ArrowThickRight);
	app.component("BatteryLow", BatteryLow);
	app.component("Folder", Folder);
	app.component("Ticket", Ticket);
	app.component("ChartBar", ChartBar);
	app.component("Plugin", Plugin);
	app.component("ZoomOut", ZoomOut);
	app.component("Thermometer", Thermometer);
	app.component("ThumbsDown", ThumbsDown);
	app.component("Reply", Reply);
	app.component("ArrowThickDown", ArrowThickDown);
	app.component("CheveronDown", CheveronDown);
	app.component("Buoy", Buoy);
	app.component("MusicPlaylist", MusicPlaylist);
	app.component("NewsPaper", NewsPaper);
	app.component("Photo", Photo);
	app.component("CheveronOutlineRight", CheveronOutlineRight);
	app.component("BorderInner", BorderInner);
	app.component("Camera", Camera);
	app.component("Envelope", Envelope);
	app.component("BorderHorizontal", BorderHorizontal);
	app.component("Window", Window);
	app.component("ViewShow", ViewShow);
	app.component("Coffee", Coffee);
	app.component("Artist", Artist);
	app.component("Refresh", Refresh);
	app.component("TravelWalk", TravelWalk);
	app.component("ListAdd", ListAdd);
	app.component("PlayOutline", PlayOutline);
	app.component("Beverage", Beverage);
	app.component("LocationFood", LocationFood);
	app.component("Phone", Phone);
	app.component("VideoCamera", VideoCamera);
	app.component("FolderOutlineAdd", FolderOutlineAdd);
	app.component("Bluetooth", Bluetooth);
	app.component("CloseOutline", CloseOutline);
	app.component("ExclamationSolid", ExclamationSolid);
	app.component("InformationSolid", InformationSolid);
	app.component("LocationShopping", LocationShopping);
	app.component("EditCopy", EditCopy);
	app.component("Notification", Notification);
	app.component("Shield", Shield);
	app.component("DateAdd", DateAdd);
	app.component("ArrowLeft", ArrowLeft);
	app.component("Education", Education);
	app.component("TravelTrain", TravelTrain);
	app.component("MoodHappyOutline", MoodHappyOutline);
	app.component("Download", Download);
	app.component("Calculator", Calculator);
	app.component("Upload", Upload);
	app.component("FormatTextSize", FormatTextSize);
	app.component("CheveronRight", CheveronRight);
	app.component("CurrencyDollar", CurrencyDollar);
};
