import YinYang from './components/yin-yang.ts';
import CheveronLeft from './components/cheveron-left.ts';
import SubdirectoryRight from './components/subdirectory-right.ts';
import Flashlight from './components/flashlight.ts';
import Link from './components/link.ts';
import SubdirectoryLeft from './components/subdirectory-left.ts';
import EditCopy from './components/edit-copy.ts';
import ViewList from './components/view-list.ts';
import Tag from './components/tag.ts';
import Backward from './components/backward.ts';
import LocationShopping from './components/location-shopping.ts';
import ArrowOutlineRight from './components/arrow-outline-right.ts';
import Key from './components/key.ts';
import Trash from './components/trash.ts';
import BookmarkCopy3 from './components/bookmark copy 3.ts';
import InboxFull from './components/inbox-full.ts';
import LockClosed from './components/lock-closed.ts';
import Pin from './components/pin.ts';
import Bug from './components/bug.ts';
import ArrowLeft from './components/arrow-left.ts';
import StandBy from './components/stand-by.ts';
import PhpElephant from './components/php-elephant.ts';
import SaveDisk from './components/save-disk.ts';
import LockOpen from './components/lock-open.ts';
import Target from './components/target.ts';
import Usb from './components/usb.ts';
import LocationPark from './components/location-park.ts';
import Anchor from './components/anchor.ts';
import Coffee from './components/coffee.ts';
import CurrencyDollar from './components/currency-dollar.ts';
import Close from './components/close.ts';
import Artist from './components/artist.ts';
import HourGlass from './components/hour-glass.ts';
import Code from './components/code.ts';
import Question from './components/question.ts';
import FormatBold from './components/format-bold.ts';
import ArrowThickUp from './components/arrow-thick-up.ts';
import LoadBalancer from './components/load-balancer.ts';
import Clipboard from './components/clipboard.ts';
import Conversation from './components/conversation.ts';
import Cloud from './components/cloud.ts';
import ArrowThinDown from './components/arrow-thin-down.ts';
import ViewColumn from './components/view-column.ts';
import Network from './components/network.ts';
import Shield from './components/shield.ts';
import Notifications from './components/notifications.ts';
import StarFull from './components/star-full.ts';
import Map from './components/map.ts';
import Factory from './components/factory.ts';
import LocationMarina from './components/location-marina.ts';
import Cog from './components/cog.ts';
import UserGroup from './components/user-group.ts';
import ZoomIn from './components/zoom-in.ts';
import Mouse from './components/mouse.ts';
import CreditCard from './components/credit-card.ts';
import VolumeDown from './components/volume-down.ts';
import ShoppingCart from './components/shopping-cart.ts';
import ChartBar from './components/chart-bar.ts';
import TravelBus from './components/travel-bus.ts';
import Inbox from './components/inbox.ts';
import BrowserWindowOpen from './components/browser-window-open.ts';
import ChartPie from './components/chart-pie.ts';
import DateAdd from './components/date-add.ts';
import BorderInner from './components/border-inner.ts';
import User from './components/user.ts';
import Location from './components/location.ts';
import BatteryLow from './components/battery-low.ts';
import BorderTop from './components/border-top.ts';
import HardDrive from './components/hard-drive.ts';
import BorderRight from './components/border-right.ts';
import Swap from './components/swap.ts';
import StoreFront from './components/store-front.ts';
import Heart from './components/heart.ts';
import BorderBottom from './components/border-bottom.ts';
import Upload from './components/upload.ts';
import CheveronUp from './components/cheveron-up.ts';
import BrightnessDown from './components/brightness-down.ts';
import Send from './components/send.ts';
import VolumeOff from './components/volume-off.ts';
import Stethoscope from './components/stethoscope.ts';
import ZoomOut from './components/zoom-out.ts';
import Timer from './components/timer.ts';
import HandStop from './components/hand-stop.ts';
import ViewCarousel from './components/view-carousel.ts';
import Travel from './components/travel.ts';
import VolumeUp from './components/volume-up.ts';
import Translate from './components/translate.ts';
import Tablet from './components/tablet.ts';
import Education from './components/education.ts';
import Tuning from './components/tuning.ts';
import Chart from './components/chart.ts';
import BatteryHalf from './components/battery-half.ts';
import ArrowOutlineLeft from './components/arrow-outline-left.ts';
import LocationHotel from './components/location-hotel.ts';
import AlignJustified from './components/align-justified.ts';
import Pause from './components/pause.ts';
import WindowNew from './components/window-new.ts';
import Duplicate from './components/duplicate.ts';
import CheveronOutlineUp from './components/cheveron-outline-up.ts';
import Announcement from './components/announcement.ts';
import FormatUnderline from './components/format-underline.ts';
import ThumbsUp from './components/thumbs-up.ts';
import Radar from './components/radar.ts';
import ArrowThickLeft from './components/arrow-thick-left.ts';
import ToolsCopy from './components/tools copy.ts';
import LocationRestroom from './components/location-restroom.ts';
import NewsPaper from './components/news-paper.ts';
import MobileDevices from './components/mobile-devices.ts';
import MinusSolid from './components/minus-solid.ts';
import BookmarkCopy2 from './components/bookmark copy 2.ts';
import ForwardStep from './components/forward-step.ts';
import MusicArtist from './components/music-artist.ts';
import Camera from './components/camera.ts';
import ExclamationSolid from './components/exclamation-solid.ts';
import BackwardStep from './components/backward-step.ts';
import Calendar from './components/calendar.ts';
import AlignLeft from './components/align-left.ts';
import AddSolid from './components/add-solid.ts';
import ArrowThinLeft from './components/arrow-thin-left.ts';
import BookmarkOutlineAdd from './components/bookmark-outline-add.ts';
import Home from './components/home.ts';
import CheveronDown from './components/cheveron-down.ts';
import AlignRight from './components/align-right.ts';
import WindowOpen from './components/window-open.ts';
import Filter from './components/filter.ts';
import Menu from './components/menu.ts';
import TextDecoration from './components/text-decoration.ts';
import Notification from './components/notification.ts';
import StepForward from './components/step-forward.ts';
import StrokeWidth from './components/stroke-width.ts';
import Bolt from './components/bolt.ts';
import Layers from './components/layers.ts';
import TextBox from './components/text-box.ts';
import Keyboard from './components/keyboard.ts';
import MoodNeutralOutline from './components/mood-neutral-outline.ts';
import Radio from './components/radio.ts';
import ColorPalette from './components/color-palette.ts';
import PauseOutline from './components/pause-outline.ts';
import TravelTaxiCab from './components/travel-taxi-cab.ts';
import Trophy from './components/trophy.ts';
import LocationFood from './components/location-food.ts';
import InboxDownload from './components/inbox-download.ts';
import Share01 from './components/share-01.ts';
import ArrowThinUp from './components/arrow-thin-up.ts';
import CheveronOutlineRight from './components/cheveron-outline-right.ts';
import Wrench from './components/wrench.ts';
import Bluetooth from './components/bluetooth.ts';
import ListBullet from './components/list-bullet.ts';
import Globe from './components/globe.ts';
import Share from './components/share.ts';
import Wallet from './components/wallet.ts';
import MinusOutline from './components/minus-outline.ts';
import MoodSadOutline from './components/mood-sad-outline.ts';
import Beverage from './components/beverage.ts';
import ArrowThickDown from './components/arrow-thick-down.ts';
import Box from './components/box.ts';
import CloseOutline from './components/close-outline.ts';
import Dashboard from './components/dashboard.ts';
import Apparel from './components/apparel.ts';
import BorderLeft from './components/border-left.ts';
import Playlist from './components/playlist.ts';
import Station from './components/station.ts';
import NotificationsOutline from './components/notifications-outline.ts';
import BookmarkOutline from './components/bookmark-outline.ts';
import ThumbsDown from './components/thumbs-down.ts';
import Repost from './components/repost.ts';
import Album from './components/album.ts';
import Backspace from './components/backspace.ts';
import ComputerDesktop from './components/computer-desktop.ts';
import LocationGasStation from './components/location-gas-station.ts';
import Directions from './components/directions.ts';
import ShowSidebar from './components/show-sidebar.ts';
import ReplyAll from './components/reply-all.ts';
import FolderOutlineAdd from './components/folder-outline-add.ts';
import Envelope from './components/envelope.ts';
import Library from './components/library.ts';
import MoodHappyOutline from './components/mood-happy-outline.ts';
import Shuffle from './components/shuffle.ts';
import InformationOutline from './components/information-outline.ts';
import ScreenFull from './components/screen-full.ts';
import AtSymbol from './components/at-symbol.ts';
import BrowserWindow from './components/browser-window.ts';
import Film from './components/film.ts';
import TravelCar from './components/travel-car.ts';
import ArrowUp from './components/arrow-up.ts';
import StepBackward from './components/step-backward.ts';
import Download from './components/download.ts';
import Pylon from './components/pylon.ts';
import ArrowRight from './components/arrow-right.ts';
import Watch from './components/watch.ts';
import Headphones from './components/headphones.ts';
import Adjust from './components/adjust.ts';
import Paste from './components/paste.ts';
import Gift from './components/gift.ts';
import PenTool from './components/pen-tool.ts';
import BatteryFull from './components/battery-full.ts';
import Thermometer from './components/thermometer.ts';
import BorderNone from './components/border-none.ts';
import ArrowThickRight from './components/arrow-thick-right.ts';
import IndentDecrease from './components/indent-decrease.ts';
import FolderOutline from './components/folder-outline.ts';
import VolumeMute from './components/volume-mute.ts';
import Flag from './components/flag.ts';
import Forward from './components/forward.ts';
import IndentIncrease from './components/indent-increase.ts';
import TravelTrain from './components/travel-train.ts';
import ArrowOutlineUp from './components/arrow-outline-up.ts';
import ViewHide from './components/view-hide.ts';
import MusicPlaylist from './components/music-playlist.ts';
import ShareAlt from './components/share-alt.ts';
import Reload from './components/reload.ts';
import Refresh from './components/refresh.ts';
import Attachment from './components/attachment.ts';
import ChatBubbleDots from './components/chat-bubble-dots.ts';
import Photo from './components/photo.ts';
import EditCrop from './components/edit-crop.ts';
import FormatTextSize from './components/format-text-size.ts';
import Phone from './components/phone.ts';
import Servers from './components/servers.ts';
import ArrowThinRight from './components/arrow-thin-right.ts';
import FastForward from './components/fast-forward.ts';
import Document from './components/document.ts';
import Bookmark from './components/bookmark.ts';
import Queue from './components/queue.ts';
import TravelCase from './components/travel-case.ts';
import UserAdd from './components/user-add.ts';
import FormatFontSize from './components/format-font-size.ts';
import Vector from './components/vector.ts';
import LocationCurrent from './components/location-current.ts';
import LightBulb from './components/light-bulb.ts';
import BorderVertical from './components/border-vertical.ts';
import BorderOuter from './components/border-outer.ts';
import DialPad from './components/dial-pad.ts';
import ExclamationOutline from './components/exclamation-outline.ts';
import Window from './components/window.ts';
import UserSolidSquare from './components/user-solid-square.ts';
import FastRewind from './components/fast-rewind.ts';
import CloudUpload from './components/cloud-upload.ts';
import ArrowOutlineDown from './components/arrow-outline-down.ts';
import BorderHorizontal from './components/border-horizontal.ts';
import List from './components/list.ts';
import Time from './components/time.ts';
import Calculator from './components/calculator.ts';
import FormatItalic from './components/format-italic.ts';
import CloseSolid from './components/close-solid.ts';
import Hot from './components/hot.ts';
import UserSolidCircle from './components/user-solid-circle.ts';
import VideoCamera from './components/video-camera.ts';
import InboxCheck from './components/inbox-check.ts';
import BrightnessUp from './components/brightness-up.ts';
import NavigationMore from './components/navigation-more.ts';
import Buoy from './components/buoy.ts';
import Plugin from './components/plugin.ts';
import Ticket from './components/ticket.ts';
import Badge from './components/badge.ts';
import BorderAll from './components/border-all.ts';
import BrowserWindowNew from './components/browser-window-new.ts';
import AddOutline from './components/add-outline.ts';
import MusicAlbum from './components/music-album.ts';
import Search from './components/search.ts';
import Mic from './components/mic.ts';
import DocumentAdd from './components/document-add.ts';
import Play from './components/play.ts';
import TravelWalk from './components/travel-walk.ts';
import BookReference from './components/book-reference.ts';
import InformationSolid from './components/information-solid.ts';
import EditPencil from './components/edit-pencil.ts';
import ViewShow from './components/view-show.ts';
import CheveronOutlineDown from './components/cheveron-outline-down.ts';
import DotsHorizontalDouble from './components/dots-horizontal-double.ts';
import MoodHappySolid from './components/mood-happy-solid.ts';
import MusicNotes from './components/music-notes.ts';
import ComputerLaptop from './components/computer-laptop.ts';
import PlayOutline from './components/play-outline.ts';
import CheveronOutlineLeft from './components/cheveron-outline-left.ts';
import Reply from './components/reply.ts';
import MoodSadSolid from './components/mood-sad-solid.ts';
import Folder from './components/folder.ts';
import EditCut from './components/edit-cut.ts';
import Printer from './components/printer.ts';
import ViewTile from './components/view-tile.ts';
import CheveronRight from './components/cheveron-right.ts';
import MoodNeutralSolid from './components/mood-neutral-solid.ts';
import DotsHorizontalTriple from './components/dots-horizontal-triple.ts';
import CheckmarkOutline from './components/checkmark-outline.ts';
import ListAdd from './components/list-add.ts';
import Portfolio from './components/portfolio.ts';
import Explore from './components/explore.ts';
import Copy from './components/copy.ts';
import ArrowDown from './components/arrow-down.ts';
import Checkmark from './components/checkmark.ts';
import Compose from './components/compose.ts';
import AlignCenter from './components/align-center.ts';
import PauseSolid from './components/pause-solid.ts';
import Block from './components/block.ts';
import Airplane from './components/airplane.ts';
export default (app) => {
app.component('YinYang', YinYang);
app.component('CheveronLeft', CheveronLeft);
app.component('SubdirectoryRight', SubdirectoryRight);
app.component('Flashlight', Flashlight);
app.component('Link', Link);
app.component('SubdirectoryLeft', SubdirectoryLeft);
app.component('EditCopy', EditCopy);
app.component('ViewList', ViewList);
app.component('Tag', Tag);
app.component('Backward', Backward);
app.component('LocationShopping', LocationShopping);
app.component('ArrowOutlineRight', ArrowOutlineRight);
app.component('Key', Key);
app.component('Trash', Trash);
app.component('BookmarkCopy3', BookmarkCopy3);
app.component('InboxFull', InboxFull);
app.component('LockClosed', LockClosed);
app.component('Pin', Pin);
app.component('Bug', Bug);
app.component('ArrowLeft', ArrowLeft);
app.component('StandBy', StandBy);
app.component('PhpElephant', PhpElephant);
app.component('SaveDisk', SaveDisk);
app.component('LockOpen', LockOpen);
app.component('Target', Target);
app.component('Usb', Usb);
app.component('LocationPark', LocationPark);
app.component('Anchor', Anchor);
app.component('Coffee', Coffee);
app.component('CurrencyDollar', CurrencyDollar);
app.component('Close', Close);
app.component('Artist', Artist);
app.component('HourGlass', HourGlass);
app.component('Code', Code);
app.component('Question', Question);
app.component('FormatBold', FormatBold);
app.component('ArrowThickUp', ArrowThickUp);
app.component('LoadBalancer', LoadBalancer);
app.component('Clipboard', Clipboard);
app.component('Conversation', Conversation);
app.component('Cloud', Cloud);
app.component('ArrowThinDown', ArrowThinDown);
app.component('ViewColumn', ViewColumn);
app.component('Network', Network);
app.component('Shield', Shield);
app.component('Notifications', Notifications);
app.component('StarFull', StarFull);
app.component('Map', Map);
app.component('Factory', Factory);
app.component('LocationMarina', LocationMarina);
app.component('Cog', Cog);
app.component('UserGroup', UserGroup);
app.component('ZoomIn', ZoomIn);
app.component('Mouse', Mouse);
app.component('CreditCard', CreditCard);
app.component('VolumeDown', VolumeDown);
app.component('ShoppingCart', ShoppingCart);
app.component('ChartBar', ChartBar);
app.component('TravelBus', TravelBus);
app.component('Inbox', Inbox);
app.component('BrowserWindowOpen', BrowserWindowOpen);
app.component('ChartPie', ChartPie);
app.component('DateAdd', DateAdd);
app.component('BorderInner', BorderInner);
app.component('User', User);
app.component('Location', Location);
app.component('BatteryLow', BatteryLow);
app.component('BorderTop', BorderTop);
app.component('HardDrive', HardDrive);
app.component('BorderRight', BorderRight);
app.component('Swap', Swap);
app.component('StoreFront', StoreFront);
app.component('Heart', Heart);
app.component('BorderBottom', BorderBottom);
app.component('Upload', Upload);
app.component('CheveronUp', CheveronUp);
app.component('BrightnessDown', BrightnessDown);
app.component('Send', Send);
app.component('VolumeOff', VolumeOff);
app.component('Stethoscope', Stethoscope);
app.component('ZoomOut', ZoomOut);
app.component('Timer', Timer);
app.component('HandStop', HandStop);
app.component('ViewCarousel', ViewCarousel);
app.component('Travel', Travel);
app.component('VolumeUp', VolumeUp);
app.component('Translate', Translate);
app.component('Tablet', Tablet);
app.component('Education', Education);
app.component('Tuning', Tuning);
app.component('Chart', Chart);
app.component('BatteryHalf', BatteryHalf);
app.component('ArrowOutlineLeft', ArrowOutlineLeft);
app.component('LocationHotel', LocationHotel);
app.component('AlignJustified', AlignJustified);
app.component('Pause', Pause);
app.component('WindowNew', WindowNew);
app.component('Duplicate', Duplicate);
app.component('CheveronOutlineUp', CheveronOutlineUp);
app.component('Announcement', Announcement);
app.component('FormatUnderline', FormatUnderline);
app.component('ThumbsUp', ThumbsUp);
app.component('Radar', Radar);
app.component('ArrowThickLeft', ArrowThickLeft);
app.component('ToolsCopy', ToolsCopy);
app.component('LocationRestroom', LocationRestroom);
app.component('NewsPaper', NewsPaper);
app.component('MobileDevices', MobileDevices);
app.component('MinusSolid', MinusSolid);
app.component('BookmarkCopy2', BookmarkCopy2);
app.component('ForwardStep', ForwardStep);
app.component('MusicArtist', MusicArtist);
app.component('Camera', Camera);
app.component('ExclamationSolid', ExclamationSolid);
app.component('BackwardStep', BackwardStep);
app.component('Calendar', Calendar);
app.component('AlignLeft', AlignLeft);
app.component('AddSolid', AddSolid);
app.component('ArrowThinLeft', ArrowThinLeft);
app.component('BookmarkOutlineAdd', BookmarkOutlineAdd);
app.component('Home', Home);
app.component('CheveronDown', CheveronDown);
app.component('AlignRight', AlignRight);
app.component('WindowOpen', WindowOpen);
app.component('Filter', Filter);
app.component('Menu', Menu);
app.component('TextDecoration', TextDecoration);
app.component('Notification', Notification);
app.component('StepForward', StepForward);
app.component('StrokeWidth', StrokeWidth);
app.component('Bolt', Bolt);
app.component('Layers', Layers);
app.component('TextBox', TextBox);
app.component('Keyboard', Keyboard);
app.component('MoodNeutralOutline', MoodNeutralOutline);
app.component('Radio', Radio);
app.component('ColorPalette', ColorPalette);
app.component('PauseOutline', PauseOutline);
app.component('TravelTaxiCab', TravelTaxiCab);
app.component('Trophy', Trophy);
app.component('LocationFood', LocationFood);
app.component('InboxDownload', InboxDownload);
app.component('Share01', Share01);
app.component('ArrowThinUp', ArrowThinUp);
app.component('CheveronOutlineRight', CheveronOutlineRight);
app.component('Wrench', Wrench);
app.component('Bluetooth', Bluetooth);
app.component('ListBullet', ListBullet);
app.component('Globe', Globe);
app.component('Share', Share);
app.component('Wallet', Wallet);
app.component('MinusOutline', MinusOutline);
app.component('MoodSadOutline', MoodSadOutline);
app.component('Beverage', Beverage);
app.component('ArrowThickDown', ArrowThickDown);
app.component('Box', Box);
app.component('CloseOutline', CloseOutline);
app.component('Dashboard', Dashboard);
app.component('Apparel', Apparel);
app.component('BorderLeft', BorderLeft);
app.component('Playlist', Playlist);
app.component('Station', Station);
app.component('NotificationsOutline', NotificationsOutline);
app.component('BookmarkOutline', BookmarkOutline);
app.component('ThumbsDown', ThumbsDown);
app.component('Repost', Repost);
app.component('Album', Album);
app.component('Backspace', Backspace);
app.component('ComputerDesktop', ComputerDesktop);
app.component('LocationGasStation', LocationGasStation);
app.component('Directions', Directions);
app.component('ShowSidebar', ShowSidebar);
app.component('ReplyAll', ReplyAll);
app.component('FolderOutlineAdd', FolderOutlineAdd);
app.component('Envelope', Envelope);
app.component('Library', Library);
app.component('MoodHappyOutline', MoodHappyOutline);
app.component('Shuffle', Shuffle);
app.component('InformationOutline', InformationOutline);
app.component('ScreenFull', ScreenFull);
app.component('AtSymbol', AtSymbol);
app.component('BrowserWindow', BrowserWindow);
app.component('Film', Film);
app.component('TravelCar', TravelCar);
app.component('ArrowUp', ArrowUp);
app.component('StepBackward', StepBackward);
app.component('Download', Download);
app.component('Pylon', Pylon);
app.component('ArrowRight', ArrowRight);
app.component('Watch', Watch);
app.component('Headphones', Headphones);
app.component('Adjust', Adjust);
app.component('Paste', Paste);
app.component('Gift', Gift);
app.component('PenTool', PenTool);
app.component('BatteryFull', BatteryFull);
app.component('Thermometer', Thermometer);
app.component('BorderNone', BorderNone);
app.component('ArrowThickRight', ArrowThickRight);
app.component('IndentDecrease', IndentDecrease);
app.component('FolderOutline', FolderOutline);
app.component('VolumeMute', VolumeMute);
app.component('Flag', Flag);
app.component('Forward', Forward);
app.component('IndentIncrease', IndentIncrease);
app.component('TravelTrain', TravelTrain);
app.component('ArrowOutlineUp', ArrowOutlineUp);
app.component('ViewHide', ViewHide);
app.component('MusicPlaylist', MusicPlaylist);
app.component('ShareAlt', ShareAlt);
app.component('Reload', Reload);
app.component('Refresh', Refresh);
app.component('Attachment', Attachment);
app.component('ChatBubbleDots', ChatBubbleDots);
app.component('Photo', Photo);
app.component('EditCrop', EditCrop);
app.component('FormatTextSize', FormatTextSize);
app.component('Phone', Phone);
app.component('Servers', Servers);
app.component('ArrowThinRight', ArrowThinRight);
app.component('FastForward', FastForward);
app.component('Document', Document);
app.component('Bookmark', Bookmark);
app.component('Queue', Queue);
app.component('TravelCase', TravelCase);
app.component('UserAdd', UserAdd);
app.component('FormatFontSize', FormatFontSize);
app.component('Vector', Vector);
app.component('LocationCurrent', LocationCurrent);
app.component('LightBulb', LightBulb);
app.component('BorderVertical', BorderVertical);
app.component('BorderOuter', BorderOuter);
app.component('DialPad', DialPad);
app.component('ExclamationOutline', ExclamationOutline);
app.component('Window', Window);
app.component('UserSolidSquare', UserSolidSquare);
app.component('FastRewind', FastRewind);
app.component('CloudUpload', CloudUpload);
app.component('ArrowOutlineDown', ArrowOutlineDown);
app.component('BorderHorizontal', BorderHorizontal);
app.component('List', List);
app.component('Time', Time);
app.component('Calculator', Calculator);
app.component('FormatItalic', FormatItalic);
app.component('CloseSolid', CloseSolid);
app.component('Hot', Hot);
app.component('UserSolidCircle', UserSolidCircle);
app.component('VideoCamera', VideoCamera);
app.component('InboxCheck', InboxCheck);
app.component('BrightnessUp', BrightnessUp);
app.component('NavigationMore', NavigationMore);
app.component('Buoy', Buoy);
app.component('Plugin', Plugin);
app.component('Ticket', Ticket);
app.component('Badge', Badge);
app.component('BorderAll', BorderAll);
app.component('BrowserWindowNew', BrowserWindowNew);
app.component('AddOutline', AddOutline);
app.component('MusicAlbum', MusicAlbum);
app.component('Search', Search);
app.component('Mic', Mic);
app.component('DocumentAdd', DocumentAdd);
app.component('Play', Play);
app.component('TravelWalk', TravelWalk);
app.component('BookReference', BookReference);
app.component('InformationSolid', InformationSolid);
app.component('EditPencil', EditPencil);
app.component('ViewShow', ViewShow);
app.component('CheveronOutlineDown', CheveronOutlineDown);
app.component('DotsHorizontalDouble', DotsHorizontalDouble);
app.component('MoodHappySolid', MoodHappySolid);
app.component('MusicNotes', MusicNotes);
app.component('ComputerLaptop', ComputerLaptop);
app.component('PlayOutline', PlayOutline);
app.component('CheveronOutlineLeft', CheveronOutlineLeft);
app.component('Reply', Reply);
app.component('MoodSadSolid', MoodSadSolid);
app.component('Folder', Folder);
app.component('EditCut', EditCut);
app.component('Printer', Printer);
app.component('ViewTile', ViewTile);
app.component('CheveronRight', CheveronRight);
app.component('MoodNeutralSolid', MoodNeutralSolid);
app.component('DotsHorizontalTriple', DotsHorizontalTriple);
app.component('CheckmarkOutline', CheckmarkOutline);
app.component('ListAdd', ListAdd);
app.component('Portfolio', Portfolio);
app.component('Explore', Explore);
app.component('Copy', Copy);
app.component('ArrowDown', ArrowDown);
app.component('Checkmark', Checkmark);
app.component('Compose', Compose);
app.component('AlignCenter', AlignCenter);
app.component('PauseSolid', PauseSolid);
app.component('Block', Block);
app.component('Airplane', Airplane);
}